#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "build-support" / "meson" / "sources" / "meson.build"
OUT_BASE = OUT.parent
ENGINE_ROOT = "src/engine"


GROUPS = [
    ("botlib_sources", f"{ENGINE_ROOT}/botlib", ["*.c"], []),
    ("client_sources", f"{ENGINE_ROOT}/client", ["*.c"], ["cl_curl.c"]),
    ("client_curl_sources", f"{ENGINE_ROOT}/client", ["cl_curl.c"], []),
    ("qcommon_sources", f"{ENGINE_ROOT}/qcommon", ["*.c"], ["vm_aarch64.c", "vm_armv7l.c", "vm_powerpc.c", "vm_x86.c"]),
    ("qcommon_vm_x86_sources", f"{ENGINE_ROOT}/qcommon", ["vm_x86.c"], []),
    ("qcommon_vm_aarch64_sources", f"{ENGINE_ROOT}/qcommon", ["vm_aarch64.c"], []),
    ("qcommon_vm_armv7l_sources", f"{ENGINE_ROOT}/qcommon", ["vm_armv7l.c"], []),
    ("qcommon_vm_powerpc_sources", f"{ENGINE_ROOT}/qcommon", ["vm_powerpc.c"], []),
    ("renderer_common_sources", f"{ENGINE_ROOT}/renderercommon", ["*.c"], []),
    ("renderer_gl_sources", f"{ENGINE_ROOT}/renderer", ["*.c"], []),
    ("renderer2_sources", f"{ENGINE_ROOT}/renderer2", ["*.c"], ["stringify.c"]),
    ("renderer_vk_sources", f"{ENGINE_ROOT}/renderervk", ["*.c"], ["bin2hex.c"]),
    ("server_sources", f"{ENGINE_ROOT}/server", ["*.c"], ["sv_rankings.c"]),
    ("unix_core_sources", f"{ENGINE_ROOT}/unix", ["unix_main.c", "unix_shared.c", "linux_signals.c"], []),
    ("sdl_ui_sources", f"{ENGINE_ROOT}/sdl", ["*.c"], []),
    ("win32_core_sources", f"{ENGINE_ROOT}/win32", ["win_main.c", "win_shared.c", "win_syscon.c"], []),
    (
        "win32_ui_sources",
        f"{ENGINE_ROOT}/win32",
        ["win_gamma.c", "win_glimp.c", "win_input.c", "win_minimize.c", "win_snd.c", "win_wndproc.c"],
        [],
    ),
    ("win32_qgl_sources", f"{ENGINE_ROOT}/win32", ["win_qgl.c"], []),
    ("win32_qvk_sources", f"{ENGINE_ROOT}/win32", ["win_qvk.c"], []),
]

FILE_LIST_GROUPS = [
    ("renderer_shared_aux_sources", [f"{ENGINE_ROOT}/qcommon/puff.c", f"{ENGINE_ROOT}/qcommon/q_math.c", f"{ENGINE_ROOT}/qcommon/q_shared.c"]),
]

STRING_LIST_GROUPS = [
    (
        "renderer2_glsl_sources",
        sorted(
            Path(os.path.relpath(path, ROOT)).as_posix()
            for path in (ROOT / "src" / "engine" / "renderer2" / "glsl").glob("*.glsl")
        ),
    ),
]


def resolve_patterns(base: Path, patterns: list[str], excludes: list[str]) -> list[str]:
    paths: set[Path] = set()
    for pattern in patterns:
        paths.update(base.glob(pattern))

    exclude_paths: set[Path] = set()
    for pattern in excludes:
        exclude_paths.update(base.glob(pattern))

    files = [
        Path(os.path.relpath(path, OUT_BASE)).as_posix()
        for path in sorted(paths)
        if path.is_file() and path not in exclude_paths
    ]
    return files


def emit_files_block(name: str, files: list[str]) -> list[str]:
    lines = [f"{name} = files("]
    for path in files:
        lines.append(f"  '{path}',")
    lines.append(")")
    lines.append("")
    return lines


def emit_string_block(name: str, values: list[str]) -> list[str]:
    lines = [f"{name} = ["]
    for value in values:
        lines.append(f"  '{value}',")
    lines.append("]")
    lines.append("")
    return lines


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# This file is generated by scripts/generate_meson_source_lists.py.",
        "# Update the generator when source layout changes, then regenerate.",
        "",
    ]

    for name, rel_dir, patterns, excludes in GROUPS:
        files = resolve_patterns(ROOT / rel_dir, patterns, excludes)
        lines.extend(emit_files_block(name, files))

    for name, files in FILE_LIST_GROUPS:
        rel_files = [Path(os.path.relpath(ROOT / rel_path, OUT_BASE)).as_posix() for rel_path in files]
        lines.extend(emit_files_block(name, rel_files))

    for name, values in STRING_LIST_GROUPS:
        lines.extend(emit_string_block(name, values))

    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
